sudo: required
services:
  - docker

before_install: 
  - docker build -t anki17345/docker_react_nginx -f Dockerfile.dev .

script:
  - docker run -e anki17345/docker_react_nginx npm run test -- --coverage

