sudo: required
language: generic
services:
  - docker

before_install: 
  - docker build -t ankitzin/docker-react-nginx -f Dockerfile.dev .

script:
  - docker run -e CI=True ankitzin/docker-react-nginx npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react-nginx"
  env: "Docker-react-nginx-env"
  bucket_name: "elasticbeanstalk-us-east-1-734480534818"
  bucket_path: "docker-react-nginx"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"


