sudo: required
services:
  - docker

before_install: 
  - docker build -t ankitzin/docker_react_nginx -f Dockerfile.dev .

script:
  - docker run -e ankitzin/docker_react_nginx npm run test -- --coverage

